-- audit_finance_posting_preflight.sql
-- READ-ONLY pre-flight check for sql/001_finance_posting_core.sql
-- =============================================================================
-- Purpose:
--   Confirm the live fin_*/lp_* schema matches every column the 001 posting
--   functions reference, BEFORE running 001 on a database. 001 itself only adds
--   two small tables (fin_posting_config, fin_doc_sequences) and five finance-link
--   columns onto lp_invoices/lp_credit_notes; everything else it merely reads and
--   writes and therefore assumes already exists.
--
-- Safe to run anywhere: this script makes NO changes. It only SELECTs from
-- information_schema. Run it in the Supabase SQL editor on the target project
-- (ideally your test clone) and read the results top to bottom.
--
-- How to read the output:
--   * Section 1  — any required TABLE that is missing entirely.
--   * Section 2  — any required COLUMN that is missing (MISSING rows sort first).
--   * Section 3  — one-line pass/fail summary.
--   * Section 4  — informational: whether the 001 functions already exist
--                  (001 uses CREATE OR REPLACE, so pre-existing is fine).
--
-- Columns 001 ADDS itself (do NOT expect these to pre-exist; not checked here):
--   lp_invoices:      fin_ar_invoice_id, fin_journal_id, fin_posted_at, fin_posted_by, fin_posting_error
--   lp_credit_notes:  fin_ar_credit_note_id, fin_journal_id, fin_posted_at, fin_posted_by, fin_posting_error
--
-- Note: 'fin_gl_audit_log' is NON-FATAL. fin_log_audit() traps
-- undefined_table/undefined_column, so posting still works if it is absent.
-- Any MISSING row for that table is informational only.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Section 1: required tables that do not exist at all
-- ---------------------------------------------------------------------------
with required_tables (table_name) as (
  values
    ('fin_ap_invoices'),
    ('fin_ap_payment_allocations'),
    ('fin_ap_payments'),
    ('fin_ar_credit_notes'),
    ('fin_ar_customers'),
    ('fin_ar_invoice_lines'),
    ('fin_ar_invoices'),
    ('fin_ar_receipt_allocations'),
    ('fin_ar_receipts'),
    ('fin_cb_staging'),
    ('fin_gl_accounts'),
    ('fin_gl_audit_log'),
    ('fin_gl_journal_lines'),
    ('fin_gl_journals'),
    ('fin_periods'),
    ('fin_suppliers'),
    ('fin_vat_transactions'),
    ('fin_vat_types'),
    ('lp_credit_notes'),
    ('lp_invoices')
)
select 'MISSING TABLE' as issue, rt.table_name
  from required_tables rt
 where not exists (
   select 1 from information_schema.tables t
    where t.table_schema = 'public'
      and t.table_name = rt.table_name
 )
 order by rt.table_name;

-- ---------------------------------------------------------------------------
-- Section 2: required columns — MISSING first, then OK
-- ---------------------------------------------------------------------------
with expected (table_name, column_name) as (
  values
    ('lp_invoices','id'),
    ('lp_invoices','inv_status'),
    ('lp_invoices','inv_number'),
    ('lp_invoices','inv_customer'),
    ('lp_invoices','inv_date'),
    ('lp_invoices','inv_amount_incl'),
    ('lp_invoices','inv_amount_excl'),
    ('lp_invoices','inv_vat'),
    ('lp_invoices','inv_description'),
    ('lp_invoices','inv_load_no'),
    ('lp_invoices','inv_order_no'),
    ('lp_invoices','inv_approved_by'),
    ('lp_invoices','inv_approved_at'),
    ('lp_invoices','updated_at'),
    ('lp_credit_notes','id'),
    ('lp_credit_notes','cn_invoice_id'),
    ('lp_credit_notes','cn_number'),
    ('lp_credit_notes','cn_customer'),
    ('lp_credit_notes','cn_date'),
    ('lp_credit_notes','cn_vat'),
    ('lp_credit_notes','cn_description'),
    ('lp_credit_notes','cn_amount_excl'),
    ('lp_credit_notes','cn_amount_incl'),
    ('lp_credit_notes','cn_load_no'),
    ('lp_credit_notes','cn_reason'),
    ('lp_credit_notes','cn_approved_by'),
    ('lp_credit_notes','cn_approved_at'),
    ('fin_ar_customers','customer_code'),
    ('fin_ar_customers','customer_name'),
    ('fin_ar_customers','payment_terms_days'),
    ('fin_ar_customers','gl_control_account'),
    ('fin_ar_customers','default_vat_type'),
    ('fin_ar_customers','lp_client_code'),
    ('fin_suppliers','supplier_code'),
    ('fin_suppliers','supplier_name'),
    ('fin_suppliers','gl_control_account'),
    ('fin_suppliers','default_vat_type'),
    ('fin_periods','period_id'),
    ('fin_periods','entity_id'),
    ('fin_periods','period_start'),
    ('fin_periods','period_end'),
    ('fin_periods','is_closed'),
    ('fin_gl_accounts','account_code'),
    ('fin_gl_accounts','active'),
    ('fin_gl_journals','journal_id'),
    ('fin_gl_journals','entity_id'),
    ('fin_gl_journals','journal_ref'),
    ('fin_gl_journals','journal_type'),
    ('fin_gl_journals','description'),
    ('fin_gl_journals','period_id'),
    ('fin_gl_journals','journal_date'),
    ('fin_gl_journals','source_document'),
    ('fin_gl_journals','source_module'),
    ('fin_gl_journals','posted'),
    ('fin_gl_journals','posted_at'),
    ('fin_gl_journals','posted_by'),
    ('fin_gl_journals','created_by'),
    ('fin_gl_journal_lines','line_id'),
    ('fin_gl_journal_lines','journal_id'),
    ('fin_gl_journal_lines','line_number'),
    ('fin_gl_journal_lines','account_code'),
    ('fin_gl_journal_lines','description'),
    ('fin_gl_journal_lines','debit'),
    ('fin_gl_journal_lines','credit'),
    ('fin_gl_journal_lines','vat_type'),
    ('fin_gl_journal_lines','vat_amount'),
    ('fin_gl_journal_lines','reference'),
    ('fin_ar_invoices','invoice_id'),
    ('fin_ar_invoices','entity_id'),
    ('fin_ar_invoices','invoice_ref'),
    ('fin_ar_invoices','customer_code'),
    ('fin_ar_invoices','customer_invoice_no'),
    ('fin_ar_invoices','invoice_date'),
    ('fin_ar_invoices','due_date'),
    ('fin_ar_invoices','period_id'),
    ('fin_ar_invoices','status'),
    ('fin_ar_invoices','lp_load_number'),
    ('fin_ar_invoices','subtotal_excl_vat'),
    ('fin_ar_invoices','vat_amount'),
    ('fin_ar_invoices','total_incl_vat'),
    ('fin_ar_invoices','amount_received'),
    ('fin_ar_invoices','balance_due'),
    ('fin_ar_invoices','journal_id'),
    ('fin_ar_invoices','document_ref'),
    ('fin_ar_invoices','notes'),
    ('fin_ar_invoice_lines','invoice_id'),
    ('fin_ar_invoice_lines','line_number'),
    ('fin_ar_invoice_lines','description'),
    ('fin_ar_invoice_lines','gl_account_code'),
    ('fin_ar_invoice_lines','lp_load_number'),
    ('fin_ar_invoice_lines','quantity'),
    ('fin_ar_invoice_lines','unit_rate'),
    ('fin_ar_invoice_lines','subtotal_excl_vat'),
    ('fin_ar_invoice_lines','vat_type'),
    ('fin_ar_invoice_lines','vat_amount'),
    ('fin_ar_invoice_lines','line_total_incl'),
    ('fin_ar_credit_notes','cn_id'),
    ('fin_ar_credit_notes','entity_id'),
    ('fin_ar_credit_notes','cn_ref'),
    ('fin_ar_credit_notes','customer_code'),
    ('fin_ar_credit_notes','original_invoice_id'),
    ('fin_ar_credit_notes','cn_date'),
    ('fin_ar_credit_notes','period_id'),
    ('fin_ar_credit_notes','reason'),
    ('fin_ar_credit_notes','subtotal_excl_vat'),
    ('fin_ar_credit_notes','vat_amount'),
    ('fin_ar_credit_notes','total_incl_vat'),
    ('fin_ar_credit_notes','status'),
    ('fin_ar_credit_notes','journal_id'),
    ('fin_ap_invoices','invoice_id'),
    ('fin_ap_invoices','status'),
    ('fin_ap_invoices','supplier_code'),
    ('fin_ap_invoices','invoice_ref'),
    ('fin_ap_invoices','invoice_date'),
    ('fin_ap_invoices','entity_id'),
    ('fin_ap_invoices','period_id'),
    ('fin_ap_invoices','vat_amount'),
    ('fin_ap_invoices','subtotal_excl_vat'),
    ('fin_ap_invoices','total_incl_vat'),
    ('fin_ap_invoices','supplier_invoice_no'),
    ('fin_ap_invoices','journal_id'),
    ('fin_ap_invoices','amount_paid'),
    ('fin_ap_invoices','balance_due'),
    ('fin_ar_receipts','receipt_id'),
    ('fin_ar_receipts','customer_code'),
    ('fin_ar_receipts','amount'),
    ('fin_ar_receipts','amount_allocated'),
    ('fin_ar_receipts','amount_unallocated'),
    ('fin_ar_receipts','fully_allocated'),
    ('fin_ap_payments','payment_id'),
    ('fin_ap_payments','supplier_code'),
    ('fin_ap_payments','amount'),
    ('fin_ap_payments','amount_allocated'),
    ('fin_ap_payments','amount_unallocated'),
    ('fin_ap_payments','fully_allocated'),
    ('fin_ar_receipt_allocations','alloc_id'),
    ('fin_ar_receipt_allocations','receipt_id'),
    ('fin_ar_receipt_allocations','invoice_id'),
    ('fin_ar_receipt_allocations','allocated_amount'),
    ('fin_ar_receipt_allocations','allocation_date'),
    ('fin_ar_receipt_allocations','allocation_ref'),
    ('fin_ar_receipt_allocations','note'),
    ('fin_ar_receipt_allocations','created_by'),
    ('fin_ap_payment_allocations','alloc_id'),
    ('fin_ap_payment_allocations','payment_id'),
    ('fin_ap_payment_allocations','invoice_id'),
    ('fin_ap_payment_allocations','allocated_amount'),
    ('fin_ap_payment_allocations','allocation_date'),
    ('fin_ap_payment_allocations','allocation_ref'),
    ('fin_ap_payment_allocations','note'),
    ('fin_ap_payment_allocations','created_by'),
    ('fin_vat_types','vat_code'),
    ('fin_vat_types','vat_direction'),
    ('fin_vat_types','rate_pct'),
    ('fin_vat_transactions','entity_id'),
    ('fin_vat_transactions','vat_code'),
    ('fin_vat_transactions','vat_direction'),
    ('fin_vat_transactions','vat_period'),
    ('fin_vat_transactions','transaction_date'),
    ('fin_vat_transactions','tax_invoice_no'),
    ('fin_vat_transactions','counterparty_name'),
    ('fin_vat_transactions','exclusive_amount'),
    ('fin_vat_transactions','vat_amount'),
    ('fin_vat_transactions','inclusive_amount'),
    ('fin_vat_transactions','gl_account_code'),
    ('fin_vat_transactions','source_module'),
    ('fin_vat_transactions','journal_id'),
    ('fin_vat_transactions','line_id'),
    ('fin_vat_transactions','is_capital_goods'),
    ('fin_cb_staging','staging_id'),
    ('fin_cb_staging','status'),
    ('fin_cb_staging','journal_id'),
    ('fin_cb_staging','journal_ref'),
    ('fin_cb_staging','gl_account_code'),
    ('fin_cb_staging','entity_id'),
    ('fin_cb_staging','transaction_date'),
    ('fin_cb_staging','bank_account'),
    ('fin_cb_staging','direction'),
    ('fin_cb_staging','amount'),
    ('fin_cb_staging','vat_type'),
    ('fin_cb_staging','journal_description'),
    ('fin_cb_staging','description'),
    ('fin_cb_staging','import_batch'),
    ('fin_cb_staging','reference'),
    ('fin_cb_staging','posted_by'),
    ('fin_cb_staging','posted_at'),
    ('fin_gl_audit_log','table_name'),
    ('fin_gl_audit_log','record_id'),
    ('fin_gl_audit_log','action'),
    ('fin_gl_audit_log','changed_by'),
    ('fin_gl_audit_log','new_values')
)
select case when c.column_name is null then 'MISSING' else 'OK' end as status,
       e.table_name,
       e.column_name,
       case when e.table_name in ('fin_gl_audit_log') then 'non-fatal (audit only)' else '' end as note
  from expected e
  left join information_schema.columns c
    on c.table_schema = 'public'
   and c.table_name  = e.table_name
   and c.column_name = e.column_name
 order by (c.column_name is not null),   -- false (MISSING) sorts first
          e.table_name,
          e.column_name;

-- ---------------------------------------------------------------------------
-- Section 3: single pass/fail summary (ignores non-fatal audit table)
-- ---------------------------------------------------------------------------
with expected (table_name, column_name) as (
  values
    ('lp_invoices','id'),
    ('lp_invoices','inv_status'),
    ('lp_invoices','inv_number'),
    ('lp_invoices','inv_customer'),
    ('lp_invoices','inv_date'),
    ('lp_invoices','inv_amount_incl'),
    ('lp_invoices','inv_amount_excl'),
    ('lp_invoices','inv_vat'),
    ('lp_invoices','inv_description'),
    ('lp_invoices','inv_load_no'),
    ('lp_invoices','inv_order_no'),
    ('lp_invoices','inv_approved_by'),
    ('lp_invoices','inv_approved_at'),
    ('lp_invoices','updated_at'),
    ('lp_credit_notes','id'),
    ('lp_credit_notes','cn_invoice_id'),
    ('lp_credit_notes','cn_number'),
    ('lp_credit_notes','cn_customer'),
    ('lp_credit_notes','cn_date'),
    ('lp_credit_notes','cn_vat'),
    ('lp_credit_notes','cn_description'),
    ('lp_credit_notes','cn_amount_excl'),
    ('lp_credit_notes','cn_amount_incl'),
    ('lp_credit_notes','cn_load_no'),
    ('lp_credit_notes','cn_reason'),
    ('lp_credit_notes','cn_approved_by'),
    ('lp_credit_notes','cn_approved_at'),
    ('fin_ar_customers','customer_code'),
    ('fin_ar_customers','customer_name'),
    ('fin_ar_customers','payment_terms_days'),
    ('fin_ar_customers','gl_control_account'),
    ('fin_ar_customers','default_vat_type'),
    ('fin_ar_customers','lp_client_code'),
    ('fin_suppliers','supplier_code'),
    ('fin_suppliers','supplier_name'),
    ('fin_suppliers','gl_control_account'),
    ('fin_suppliers','default_vat_type'),
    ('fin_periods','period_id'),
    ('fin_periods','entity_id'),
    ('fin_periods','period_start'),
    ('fin_periods','period_end'),
    ('fin_periods','is_closed'),
    ('fin_gl_accounts','account_code'),
    ('fin_gl_accounts','active'),
    ('fin_gl_journals','journal_id'),
    ('fin_gl_journals','entity_id'),
    ('fin_gl_journals','journal_ref'),
    ('fin_gl_journals','journal_type'),
    ('fin_gl_journals','description'),
    ('fin_gl_journals','period_id'),
    ('fin_gl_journals','journal_date'),
    ('fin_gl_journals','source_document'),
    ('fin_gl_journals','source_module'),
    ('fin_gl_journals','posted'),
    ('fin_gl_journals','posted_at'),
    ('fin_gl_journals','posted_by'),
    ('fin_gl_journals','created_by'),
    ('fin_gl_journal_lines','line_id'),
    ('fin_gl_journal_lines','journal_id'),
    ('fin_gl_journal_lines','line_number'),
    ('fin_gl_journal_lines','account_code'),
    ('fin_gl_journal_lines','description'),
    ('fin_gl_journal_lines','debit'),
    ('fin_gl_journal_lines','credit'),
    ('fin_gl_journal_lines','vat_type'),
    ('fin_gl_journal_lines','vat_amount'),
    ('fin_gl_journal_lines','reference'),
    ('fin_ar_invoices','invoice_id'),
    ('fin_ar_invoices','entity_id'),
    ('fin_ar_invoices','invoice_ref'),
    ('fin_ar_invoices','customer_code'),
    ('fin_ar_invoices','customer_invoice_no'),
    ('fin_ar_invoices','invoice_date'),
    ('fin_ar_invoices','due_date'),
    ('fin_ar_invoices','period_id'),
    ('fin_ar_invoices','status'),
    ('fin_ar_invoices','lp_load_number'),
    ('fin_ar_invoices','subtotal_excl_vat'),
    ('fin_ar_invoices','vat_amount'),
    ('fin_ar_invoices','total_incl_vat'),
    ('fin_ar_invoices','amount_received'),
    ('fin_ar_invoices','balance_due'),
    ('fin_ar_invoices','journal_id'),
    ('fin_ar_invoices','document_ref'),
    ('fin_ar_invoices','notes'),
    ('fin_ar_invoice_lines','invoice_id'),
    ('fin_ar_invoice_lines','line_number'),
    ('fin_ar_invoice_lines','description'),
    ('fin_ar_invoice_lines','gl_account_code'),
    ('fin_ar_invoice_lines','lp_load_number'),
    ('fin_ar_invoice_lines','quantity'),
    ('fin_ar_invoice_lines','unit_rate'),
    ('fin_ar_invoice_lines','subtotal_excl_vat'),
    ('fin_ar_invoice_lines','vat_type'),
    ('fin_ar_invoice_lines','vat_amount'),
    ('fin_ar_invoice_lines','line_total_incl'),
    ('fin_ar_credit_notes','cn_id'),
    ('fin_ar_credit_notes','entity_id'),
    ('fin_ar_credit_notes','cn_ref'),
    ('fin_ar_credit_notes','customer_code'),
    ('fin_ar_credit_notes','original_invoice_id'),
    ('fin_ar_credit_notes','cn_date'),
    ('fin_ar_credit_notes','period_id'),
    ('fin_ar_credit_notes','reason'),
    ('fin_ar_credit_notes','subtotal_excl_vat'),
    ('fin_ar_credit_notes','vat_amount'),
    ('fin_ar_credit_notes','total_incl_vat'),
    ('fin_ar_credit_notes','status'),
    ('fin_ar_credit_notes','journal_id'),
    ('fin_ap_invoices','invoice_id'),
    ('fin_ap_invoices','status'),
    ('fin_ap_invoices','supplier_code'),
    ('fin_ap_invoices','invoice_ref'),
    ('fin_ap_invoices','invoice_date'),
    ('fin_ap_invoices','entity_id'),
    ('fin_ap_invoices','period_id'),
    ('fin_ap_invoices','vat_amount'),
    ('fin_ap_invoices','subtotal_excl_vat'),
    ('fin_ap_invoices','total_incl_vat'),
    ('fin_ap_invoices','supplier_invoice_no'),
    ('fin_ap_invoices','journal_id'),
    ('fin_ap_invoices','amount_paid'),
    ('fin_ap_invoices','balance_due'),
    ('fin_ar_receipts','receipt_id'),
    ('fin_ar_receipts','customer_code'),
    ('fin_ar_receipts','amount'),
    ('fin_ar_receipts','amount_allocated'),
    ('fin_ar_receipts','amount_unallocated'),
    ('fin_ar_receipts','fully_allocated'),
    ('fin_ap_payments','payment_id'),
    ('fin_ap_payments','supplier_code'),
    ('fin_ap_payments','amount'),
    ('fin_ap_payments','amount_allocated'),
    ('fin_ap_payments','amount_unallocated'),
    ('fin_ap_payments','fully_allocated'),
    ('fin_ar_receipt_allocations','alloc_id'),
    ('fin_ar_receipt_allocations','receipt_id'),
    ('fin_ar_receipt_allocations','invoice_id'),
    ('fin_ar_receipt_allocations','allocated_amount'),
    ('fin_ar_receipt_allocations','allocation_date'),
    ('fin_ar_receipt_allocations','allocation_ref'),
    ('fin_ar_receipt_allocations','note'),
    ('fin_ar_receipt_allocations','created_by'),
    ('fin_ap_payment_allocations','alloc_id'),
    ('fin_ap_payment_allocations','payment_id'),
    ('fin_ap_payment_allocations','invoice_id'),
    ('fin_ap_payment_allocations','allocated_amount'),
    ('fin_ap_payment_allocations','allocation_date'),
    ('fin_ap_payment_allocations','allocation_ref'),
    ('fin_ap_payment_allocations','note'),
    ('fin_ap_payment_allocations','created_by'),
    ('fin_vat_types','vat_code'),
    ('fin_vat_types','vat_direction'),
    ('fin_vat_types','rate_pct'),
    ('fin_vat_transactions','entity_id'),
    ('fin_vat_transactions','vat_code'),
    ('fin_vat_transactions','vat_direction'),
    ('fin_vat_transactions','vat_period'),
    ('fin_vat_transactions','transaction_date'),
    ('fin_vat_transactions','tax_invoice_no'),
    ('fin_vat_transactions','counterparty_name'),
    ('fin_vat_transactions','exclusive_amount'),
    ('fin_vat_transactions','vat_amount'),
    ('fin_vat_transactions','inclusive_amount'),
    ('fin_vat_transactions','gl_account_code'),
    ('fin_vat_transactions','source_module'),
    ('fin_vat_transactions','journal_id'),
    ('fin_vat_transactions','line_id'),
    ('fin_vat_transactions','is_capital_goods'),
    ('fin_cb_staging','staging_id'),
    ('fin_cb_staging','status'),
    ('fin_cb_staging','journal_id'),
    ('fin_cb_staging','journal_ref'),
    ('fin_cb_staging','gl_account_code'),
    ('fin_cb_staging','entity_id'),
    ('fin_cb_staging','transaction_date'),
    ('fin_cb_staging','bank_account'),
    ('fin_cb_staging','direction'),
    ('fin_cb_staging','amount'),
    ('fin_cb_staging','vat_type'),
    ('fin_cb_staging','journal_description'),
    ('fin_cb_staging','description'),
    ('fin_cb_staging','import_batch'),
    ('fin_cb_staging','reference'),
    ('fin_cb_staging','posted_by'),
    ('fin_cb_staging','posted_at'),
    ('fin_gl_audit_log','table_name'),
    ('fin_gl_audit_log','record_id'),
    ('fin_gl_audit_log','action'),
    ('fin_gl_audit_log','changed_by'),
    ('fin_gl_audit_log','new_values')
)
select count(*) filter (
         where c.column_name is null
           and e.table_name not in ('fin_gl_audit_log')
       ) as blocking_missing_columns,
       count(*) filter (
         where c.column_name is null
           and e.table_name in ('fin_gl_audit_log')
       ) as nonfatal_missing_columns,
       case when count(*) filter (
              where c.column_name is null
                and e.table_name not in ('fin_gl_audit_log')
            ) = 0
            then 'PASS - schema matches 001; safe to run 001'
            else 'FAIL - resolve blocking MISSING columns in Section 2 first'
       end as verdict
  from expected e
  left join information_schema.columns c
    on c.table_schema = 'public'
   and c.table_name  = e.table_name
   and c.column_name = e.column_name;

-- ---------------------------------------------------------------------------
-- Section 4: informational — do the 001 posting functions already exist?
-- (001 uses CREATE OR REPLACE, so 'already present' is not a problem.)
-- ---------------------------------------------------------------------------
select routine_name,
       'already present (CREATE OR REPLACE will update it)' as note
  from information_schema.routines
 where routine_schema = 'public'
   and routine_name in (
     'fin_post_lp_invoice','fin_post_lp_credit_note','fin_post_ap_invoice',
     'fin_post_cashbook_staging','fin_allocate_ar_receipt','fin_allocate_ap_payment'
   )
 order by routine_name;
