-- ============================================================
-- ARCHIVED — migration_001_roles_invoices.sql
-- ============================================================
-- This file has been superseded by the updated schema.sql.
--
-- The role constraint (Issue 9) and status constraint (Issue 10)
-- that this file attempted to fix are now correct in schema.sql.
--
-- The duplicate table definitions (lp_notifications, lp_invoices,
-- lp_credit_notes, lp_config, lp_user_approvals, sequences, etc.)
-- that existed in both this file and schema_update_fix6.sql have
-- been consolidated into schema.sql (Issues 2–8).
--
-- DO NOT RUN this file. Run schema.sql for a fresh install.
-- ============================================================
