-- ============================================================
-- ARCHIVED — schema_update_fix6.sql
-- ============================================================
-- This file has been superseded by the updated schema.sql.
--
-- All tables that were created here (Part A) are now included
-- directly in schema.sql with the correct column definitions,
-- RLS policies, and indexes.
--
-- Part B tables (lp_service_cards, lp_vehicle_audit, lp_anomalies,
-- lp_client_rates, etc.) are also now in schema.sql.
--
-- DO NOT RUN this file. It is retained for git history only.
-- Run schema.sql for a fresh install.
-- ============================================================
